title: Safyrus's homepage
description: >- # this means to ignore newlines until "baseurl:"
  This is a very interesting description
baseurl: ""
url: "https://safyrus.github.io"
github_username: safyrus
author: Safyrus

# Build settings
theme: jekyll-theme-console
plugins:

# Theme settings
header_pages:
  - index.markdown
style: dark
footer: 'RECOVERY MODE'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
